#!/bin/bash

function genIOSBundle() {
    mkdir -p tools/www/ios/www
    react-native bundle \
        --platform ios \
        --reset-cache \
        --verbose \
        --entry-file index.ios.js \
        --bundle-output ./tools/www/ios/www/index.ios.bundle \
        --assets-dest ./tools/www/ios/www \
        --dev false
}

function genAndroidBundle() {
    mkdir -p tools/www/android/www
    react-native bundle \
        --platform android \
        --reset-cache \
        --verbose \
        --entry-file index.android.js \
        --bundle-output ./tools/www/android/www/index.android.bundle \
        --assets-dest ./tools/www/android/www \
        --dev false
}

function zipWWW() {
    node -e "!function(){function i(e,r){var o=n.readdirSync(e);o.forEach(function(o){var s=e+'/'+o;n.statSync(s).isDirectory()?i(s,r+'/'+o):c.folder(r).file(o,n.readFileSync(s))})}function e(e,r,o){r=r||'',o=o||e+'.zip',i(e,r);var s=c.generate({base64:!1,compression:'DEFLATE'});n.writeFile(o,s,'binary',function(){console.log('success')})}var r=require('jszip'),n=require('fs'),c=new r,o=process.argv.splice(1);e.apply(null,o)}();"  www www www.zip
}

function zipAndroid() {
    cd ./tools/www/android
    zipWWW
    cd ../..
    mv ./www/android/www.zip ../../server/public/download/apks/admin/apks/jsAndroid/jsandroid.zip
    rm -fr www
    echo "../../server/public/download/apks/admin/apks/jsAndroid/jsandroid.zip"
}

function zipIos() {
    cd ./tools/www/ios
    zipWWW
    cd ../..
    mv ./www/ios/www.zip ../../server/public/download/apks/admin/apks/jsIos/jsios.zip
    rm -fr www
    echo "../../server/public/download/apks/admin/apks/jsIos/jsios.zip"
}

function buildAndroid() {
    rm -fr www
    mkdir www
    cd ..
    genAndroidBundle
    zipAndroid
}

function buildIos() {
    rm -fr www
    mkdir www
    cd ..
    genIOSBundle
    zipIos
}

function main() {
    if [ "$1" = "android" ];then
        buildAndroid
    elif [ "$1" = "ios" ];then
        buildIos
    else
        buildAndroid
        buildIos
    fi
}

main $@
