#!/bin/bash

function __get_extname()
{
    local basename extname file
    file="$1"
    [ -z "$file" ]&&echo ""&&return
    [ "$file" = "." ]&&echo "."&&return

    basename=$(basename $file)
    extname=${basename/#*./}
    [ "$extname" = "" ]&&extname="."
    [ "$extname" = "$basename" ]&&extname=""
    echo "$extname"
}
function __get_pure_filename()
{
    local file extname purename
    file="$1"
    [ -z "$file" ]&&echo ""&&return
    [ "$file" = "." ]&&echo "."&&return

    extname=`__get_extname ${file}`
    [ "$extname" = "" ]&&purename=${file}

    basename=$(basename $file)
    purename=${basename/%.${extname}/}
    echo "$purename"
}

last_name=""
file=image.js
echo "module.exports = {" > $file
modules=(`ls image`)
for module in ${modules[@]};do
    files=(`ls image/${module}`)
    for item in ${files[@]};do
        purefilename=`__get_pure_filename $item`
        purefilename=${purefilename%%@*}
        extfilename=`__get_extname ${item}`
        if [ "${last_name}" != "${purefilename}" ];then
            last_name=${purefilename}
            echo "    ${module}_${purefilename}:require('./image/${module}/${purefilename}.${extfilename}')," >> $file
        fi
    done
done
echo "};" >> $file
