#!/bin/bash

function __get_extname()
{
    local basename extname file
    file="$1"
    [ -z "$file" ]&&echo ""&&return
    [ "$file" = "." ]&&echo "."&&return

    basename=$(basename $file)
    extname=${basename/#*./}
    [ "$extname" = "" ]&&extname="."
    [ "$extname" = "$basename" ]&&extname=""
    echo "$extname"
}
function __get_pure_filename()
{
    local file extname purename
    file="$1"
    [ -z "$file" ]&&echo ""&&return
    [ "$file" = "." ]&&echo "."&&return

    extname=`__get_extname ${file}`
    [ "$extname" = "" ]&&purename=${file}

    basename=$(basename $file)
    purename=${basename/%.${extname}/}
    echo "$purename"
}

last_name=""
file=remobile_cocos2dx_resource.js
modules=(`ls remobile-cocos2dx-resource`)
echo "var resolveAssetSource = require('resolveAssetSource');" > "$file"
echo "module.exports = {" >> "$file"

img="     img: {"
plist="     plist: {"
for module in ${modules[@]};do
    files=(`ls remobile-cocos2dx-resource/${module}`)
    for item in ${files[@]};do
        purefilename=`__get_pure_filename $item`
        purefilename=${purefilename%%@*}
        extfilename=`__get_extname ${item}`
        if [ "${last_name}" != "${purefilename}" ];then
            if [ "${extfilename}" = "png" -o "${extfilename}" = "jpg" -o "${extfilename}" = "gif" ];then
                last_name=${purefilename}
                img="${img}\n        ${module}_${purefilename}:resolveAssetSource(require('./remobile-cocos2dx-resource/${module}/${purefilename}.${extfilename}')).uri,"
            elif [ "${extfilename}" = "plist" ];then
                plist="${plist}\n        ${module}_${purefilename}:resolveAssetSource(require('./remobile-cocos2dx-resource/${module}/${purefilename}.${extfilename}')).uri,"
            fi
        fi
    done
done
img="${img}\n    },"
plist="${plist}\n    },"

echo -e "${img}" >> "$file"
echo -e "${plist}" >> "$file"
echo "};" >> "$file"
