module.exports = {
	Button: require('./Button.js'),
	PageList: require('./PageList.js'),
	ActionSheet: require('./ActionSheet/index.js'),
	CustomSheet: require('./CustomSheet.js'),	ClipRect: require('./ClipRect.js'),
	Modal: require('./Modal.js'),
	DImage: require('./DImage.js'),
	Label: require('./Label.js'),
	ProgressBar: require('./ProgressBar.js'),
	Slider: require('./Slider.js'),
	MessageBox: require('./MessageBox.js'),
	WebviewMessageBox: require('./WebviewMessageBox.js'),
	DelayTouchableOpacity: require('./DelayTouchableOpacity.js'),
	StarBar: require('./StarBar.js'),
	ProgressHud: require('./ProgressHud.js'),
	RText: require('./RText.js'),
	ScoreSelect: require('./ScoreSelect.js'),
	AutogrowInput: require('./AutogrowInput.js'),
};
