#!/bin/bash
cd ../../project/App/node_modules/@remobile
dirs=(`ls`)
curdir=`pwd`

for dir in ${dirs[@]};do
    [ $dir = "tools" ]&&continue
    echo ===============================${dir}=============================
    git ci -m "eslint code"
    git pu
    cd ${curdir}
    echo
    echo
    echo
done
