#!/bin/bash

newname=$1
oldname="JFBSample"
project_old="../project"
project_new="project_new"
backup=".backup"

[ -z "$newname" ]&&echo "input newname[e.g:YXjqd]"&&exit
[ -d "${project_new}" ]&&echo "${project_new} have exist"&&exit

lnewname=$(echo ${newname}|tr '[A-Z]' '[a-z]')
loldname=$(echo ${oldname}|tr '[A-Z]' '[a-z]')

mkdir -p ${backup}
mv ${project_old}/node_modules ${backup}/node_modules
mv ${project_old}/App/node_modules ${backup}/app_node_modules
mv ${project_old}/android/build ${backup}/build
mv ${project_old}/android/app/build ${backup}/app_build
mv ${project_old}/android/.gradle ${backup}/gradle
mv ${project_old}/android/.idea ${backup}/idea
mv ${project_old}/ios/build ${backup}/ios_build
mv ${project_old}/ios/JFBSample.xcodeproj/project.xcworkspace/xcshareddata ${backup}/xcworkspace_xcshareddata
mv ${project_old}/ios/JFBSample.xcodeproj/project.xcworkspace/xcuserdata ${backup}/xcworkspace_xcuserdata
mv ${project_old}/ios/JFBSample.xcodeproj/xcshareddata ${backup}/xcshareddata
mv ${project_old}/ios/JFBSample.xcodeproj/xcuserdata ${backup}/xcuserdata

cp -r ${project_old} ${project_new}
pushd ${project_new}
xfind -t "${oldname}" -v "-c \"%s/${oldname}/${newname}/g\""
xfind -t "${loldname}" -v "-c \"%s/${loldname}/${lnewname}/g\""
popd

mv ${backup}/node_modules ${project_old}/node_modules
mv ${backup}/app_node_modules ${project_old}/App/node_modules
mv ${backup}/build ${project_old}/android/build
mv ${backup}/app_build ${project_old}/android/app/build
mv ${backup}/gradle ${project_old}/android/.gradle
mv ${backup}/idea ${project_old}/android/.idea
mv ${backup}/ios_build ${project_old}/ios/build
mv ${backup}/xcworkspace_xcshareddata ${project_old}/ios/JFBSample.xcodeproj/project.xcworkspace/xcshareddata
mv ${backup}/xcworkspace_xcuserdata ${project_old}/ios/JFBSample.xcodeproj/project.xcworkspace/xcuserdata
mv ${backup}/xcshareddata ${project_old}/ios/JFBSample.xcodeproj/xcshareddata
mv ${backup}/xcuserdata ${project_old}/ios/JFBSample.xcodeproj/xcuserdata
